import { chromium } from 'playwright';
const SHOTS=process.argv[2];
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto('https://freebirdsg.passivecoder.com/login',{waitUntil:'domcontentloaded'});
await p.fill('input[type=email]','walibdpro@gmail.com');
await p.fill('input[type=password]','Itsn0t@p@ssw0rd');
await p.click('button[type=submit]');
await p.waitForURL(/dashboard/,{timeout:60000});
await p.goto('https://freebirdsg.passivecoder.com/dashboard/header-builder?target=header&returnTo=%2Fdashboard%2Fpages',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(6000);
await p.screenshot({path:SHOTS+'/final-header.png'});
console.log('nav box:', await p.locator('[data-testid=canvas-block] nav').first().boundingBox().catch(()=>null));
// Footer must NOT get the dark ground.
await p.goto('https://freebirdsg.passivecoder.com/dashboard/header-builder?target=footer',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(5000);
await p.screenshot({path:SHOTS+'/final-footer.png'});
console.log('errors:',errs.slice(0,3));
await b.close();
