import { chromium } from 'playwright';
const OUT = process.argv[2];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1600, height: 1000 } });
const page = await ctx.newPage();
await page.goto('https://passivecoder.com/login', { waitUntil: 'networkidle' });
await page.fill('input[type="email"]', 'walibdpro@gmail.com');
await page.fill('input[type="password"]', 'Itsn0t@p@ssw0rd');
await page.click('button[type="submit"]');
await page.waitForTimeout(3000);
await page.goto('https://passivecoder.com/dashboard/pages/1e393fc6-031c-4681-a37b-e022d972f256', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(1500);
await page.locator('button', { hasText: /^Blocks$/ }).nth(1).click({ timeout: 5000 });
await page.waitForTimeout(400);
const box = page.locator('input[placeholder*="Search blocks" i]');
await box.click();
await box.type('Eligibility', { delay: 50 });
await page.waitForTimeout(800);
const buttons = await page.locator('button, div[role="button"]').allTextContents();
console.log('matches:', JSON.stringify(buttons.filter(t => t.toLowerCase().includes('eligib'))));
console.log('no-blocks-found visible:', await page.locator('text=No blocks found').count());
await page.screenshot({ path: `${OUT}/debug-search3.png` });
await b.close();
