import type { BlockType, Block, BlockBackground } from "@/types/cms";
import { generateId } from "@/lib/utils";

export type BlockDefinition = {
  type: BlockType;
  label: string;
  description: string;
  icon: string;
  category: "layout" | "content" | "media" | "ecommerce" | "interactive";
  create: () => Block;
};

const defaultBackground: BlockBackground = { type: "none" };
const defaultPadding = { top: 64, right: 24, bottom: 64, left: 24 };
const defaultMargin = { top: 0, right: 0, bottom: 0, left: 0 };

const baseBlock = (type: BlockType) => ({
  id: generateId(),
  type,
  order: 0,
  visible: true,
  width: "full" as const,
  padding: defaultPadding,
  margin: defaultMargin,
  background: defaultBackground,
  animation: "none" as const,
});

export const blockRegistry: BlockDefinition[] = [
  {
    type: "enm_lead_form",
    label: "ENM Lead Form",
    description: "Contact form that sends leads directly to your ExpertNear.Me CRM",
    icon: "📨",
    category: "interactive",
    create: () => ({
      ...baseBlock("enm_lead_form"),
      type: "enm_lead_form",
      data: {
        apiKey: "",
        formTitle: "Get in Touch",
        buttonLabel: "Send Message",
        thankYouMessage: "Thanks! We'll be in touch soon.",
        showPhone: true,
        showMessage: true,
      },
    }),
  },
  {
    type: "enm_booking_widget",
    label: "ENM Booking Widget",
    description: "Embedded booking form from your ExpertNear.Me profile",
    icon: "📅",
    category: "interactive",
    create: () => ({
      ...baseBlock("enm_booking_widget"),
      type: "enm_booking_widget",
      data: {
        expertSlug: "",
        label: "Book a Session",
        height: 600,
        maxWidth: 400,
        borderRadius: 12,
      },
    }),
  },
  {
    type: "hero",
    label: "Welcome Banner",
    description: "The big section at the top of your page — headline, photo, and buttons",
    icon: "🦸",
    category: "layout",
    create: () => ({
      ...baseBlock("hero"),
      type: "hero",
      data: {
        layout: "centered",
        title: "Welcome to Our Website",
        subtitle: "Tagline goes here",
        description: "Add a compelling description that explains what you offer and why visitors should care.",
        primaryButton: { label: "Get Started", url: "#", variant: "primary" },
        secondaryButton: { label: "Learn More", url: "#", variant: "outline" },
        typography: { titleSize: "5xl", titleColor: "#111827", subtitleColor: "#6B7280", descColor: "#6B7280" },
      },
    }),
  },
  {
    type: "slider",
    label: "Image Slideshow",
    description: "Rotating photos with optional text on top",
    icon: "🎠",
    category: "media",
    create: () => ({
      ...baseBlock("slider"),
      type: "slider",
      data: {
        slides: [
          { id: generateId(), title: "Slide One", subtitle: "Your subtitle here", imageUrl: "", buttonLabel: "Learn More", buttonUrl: "#", overlay: true },
          { id: generateId(), title: "Slide Two", subtitle: "Another subtitle", imageUrl: "", buttonLabel: "Get Started", buttonUrl: "#", overlay: true },
        ],
        autoPlay: true,
        autoPlayInterval: 5000,
        showArrows: true,
        showDots: true,
        height: "600px",
      },
    }),
  },
  {
    type: "navigation",
    label: "Menu Bar",
    description: "The strip at the very top with your logo and page links",
    icon: "🧭",
    category: "layout",
    create: () => ({
      ...baseBlock("navigation"),
      padding: { top: 0, right: 24, bottom: 0, left: 24 },
      type: "navigation",
      data: {
        logoText: "Brand",
        items: [
          { id: generateId(), label: "Home", url: "/" },
          { id: generateId(), label: "About", url: "/about" },
          { id: generateId(), label: "Services", url: "/services" },
          { id: generateId(), label: "Contact", url: "/contact" },
        ],
        sticky: true,
        transparent: false,
        style: "default",
        showCta: true,
        ctaLabel: "Get in Touch",
        ctaUrl: "/contact",
      },
    }),
  },
  {
    type: "text",
    label: "Text",
    description: "Plain writing — paragraphs, headings, lists, and links",
    icon: "📝",
    category: "content",
    create: () => ({
      ...baseBlock("text"),
      type: "text",
      data: {
        content: "<h2>Section Title</h2><p>Add your content here. This block supports <strong>rich text</strong> formatting, including bold, italic, links, and more.</p>",
        alignment: "left",
        columns: 1,
        typography: { color: "#374151" },
      },
    }),
  },
  {
    type: "services",
    label: "Services",
    description: "Cards that show what you offer, each with a short description",
    icon: "⚙️",
    category: "content",
    create: () => ({
      ...baseBlock("services"),
      type: "services",
      data: {
        title: "Our Services",
        subtitle: "What we offer",
        layout: "grid",
        columns: 3,
        cardStyle: "elevated",
        items: [
          { id: generateId(), icon: "Zap", iconType: "lucide", title: "Service One", description: "Describe this service and how it benefits your customers.", link: "#", linkLabel: "Learn More" },
          { id: generateId(), icon: "Shield", iconType: "lucide", title: "Service Two", description: "Describe this service and how it benefits your customers.", link: "#", linkLabel: "Learn More" },
          { id: generateId(), icon: "Star", iconType: "lucide", title: "Service Three", description: "Describe this service and how it benefits your customers.", link: "#", linkLabel: "Learn More" },
        ],
      },
    }),
  },
  {
    type: "blog",
    label: "Blog Posts",
    description: "Automatically shows your latest news or blog articles",
    icon: "📰",
    category: "content",
    create: () => ({
      ...baseBlock("blog"),
      type: "blog",
      data: {
        title: "Latest Posts",
        subtitle: "Stay up to date",
        displayCount: 3,
        layout: "grid",
        columns: 3,
        showExcerpt: true,
        showDate: true,
        showAuthor: true,
        showCategory: true,
        showReadMore: true,
        viewAllUrl: "/blog",
        viewAllLabel: "View All Posts",
      },
    }),
  },
  {
    type: "gallery",
    label: "Photo Gallery",
    description: "A grid of photos — great for showing off your work",
    icon: "🖼️",
    category: "media",
    create: () => ({
      ...baseBlock("gallery"),
      type: "gallery",
      data: {
        title: "Gallery",
        layout: "grid",
        columns: 3,
        gap: "md",
        images: [],
        lightbox: true,
      },
    }),
  },
  {
    type: "cta",
    label: "Action Banner",
    description: "A bold colored strip that asks visitors to call or book",
    icon: "📣",
    category: "layout",
    create: () => ({
      ...baseBlock("cta"),
      background: { type: "color", color: "#1e40af" },
      type: "cta",
      data: {
        title: "Ready to Get Started?",
        description: "Join thousands of users who trust our platform.",
        primaryButton: { label: "Start Free Trial", url: "#" },
        secondaryButton: { label: "Learn More", url: "#" },
        layout: "centered",
      },
    }),
  },
  {
    type: "testimonials",
    label: "Customer Reviews",
    description: "Quotes from happy customers with star ratings",
    icon: "💬",
    category: "content",
    create: () => ({
      ...baseBlock("testimonials"),
      type: "testimonials",
      data: {
        title: "What Our Clients Say",
        layout: "grid",
        items: [
          { id: generateId(), name: "Jane Doe", role: "CEO", company: "Acme Inc.", content: "This product completely transformed our workflow. Highly recommended!", rating: 5 },
          { id: generateId(), name: "John Smith", role: "Developer", company: "Tech Co.", content: "Excellent service and great customer support. Would use again.", rating: 5 },
          { id: generateId(), name: "Alice Lee", role: "Designer", company: "Creative Studio", content: "The best tool we have used. It saves us hours every week.", rating: 5 },
        ],
      },
    }),
  },
  {
    type: "divider",
    label: "Divider Line",
    description: "A thin line that separates two sections",
    icon: "➖",
    category: "layout",
    create: () => ({
      ...baseBlock("divider"),
      padding: { top: 16, right: 24, bottom: 16, left: 24 },
      type: "divider",
      data: { style: "solid", color: "#e5e7eb", thickness: 1, width: "full" },
    }),
  },
  {
    type: "spacer",
    label: "Empty Space",
    description: "Adds breathing room between sections",
    icon: "↕️",
    category: "layout",
    create: () => ({
      ...baseBlock("spacer"),
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      type: "spacer",
      data: { height: 80 },
    }),
  },
  {
    type: "ecommerce_products",
    label: "Products",
    description: "Automatically shows products from your online store",
    icon: "🛍️",
    category: "ecommerce",
    create: () => ({
      ...baseBlock("ecommerce_products"),
      type: "ecommerce_products",
      data: {
        title: "Featured Products",
        subtitle: "",
        displayCount: 4,
        layout: "grid",
        columns: 4,
        sortBy: "featured",
        showAddToCart: true,
        showDescription: true,
        showBadges: true,
        showRating: false,
        cardStyle: "default",
        imageRatio: "square",
        sectionPadding: "md",
        titleAlignment: "center",
        ctaLabel: "",
        ctaUrl: "",
      },
    }),
  },
  {
    type: "accounting_feed",
    label: "Donation / Transaction Feed",
    description: "Live feed of public transactions (donations, etc.)",
    icon: "💰",
    category: "interactive",
    create: () => ({
      ...baseBlock("accounting_feed"),
      type: "accounting_feed",
      data: {
        title: "Recent Donations",
        displayCount: 10,
        transactionType: "donation",
        showAmount: true,
        showDate: true,
        showMessage: true,
        layout: "list",
      },
    }),
  },
  {
    type: "ecommerce_cart",
    label: "Shopping Cart",
    description: "Display the shopping cart with checkout button",
    icon: "🛒",
    category: "ecommerce",
    create: () => ({
      ...baseBlock("ecommerce_cart"),
      type: "ecommerce_cart",
      data: { showOrderSummary: true, showCouponField: true, layout: "default" },
    }),
  },
  {
    type: "custom_html",
    label: "Custom Code (Advanced)",
    description: "For developers — paste your own HTML code",
    icon: "💻",
    category: "interactive",
    create: () => ({
      ...baseBlock("custom_html"),
      type: "custom_html",
      data: { html: "<!-- Add your custom HTML here -->" },
    }),
  },
  {
    type: "team",
    label: "Meet the Team",
    description: "Photos and names of the people behind your business",
    icon: "👥",
    category: "content",
    create: () => ({
      ...baseBlock("team"),
      type: "team",
      data: {
        title: "Meet the Team",
        subtitle: "The people behind our work",
        layout: "grid",
        columns: 3,
        showBio: true,
        showSocial: true,
        members: [
          { id: generateId(), name: "Jane Doe", role: "CEO & Founder", bio: "Passionate leader with 10+ years of experience." },
          { id: generateId(), name: "John Smith", role: "Lead Developer", bio: "Full-stack engineer who loves clean code." },
          { id: generateId(), name: "Alice Lee", role: "Designer", bio: "Creative mind shaping beautiful experiences." },
        ],
      },
    }),
  },
  {
    type: "faq",
    label: "Questions & Answers",
    description: "Common customer questions that open when clicked",
    icon: "❓",
    category: "content",
    create: () => ({
      ...baseBlock("faq"),
      type: "faq",
      data: {
        title: "Frequently Asked Questions",
        subtitle: "Everything you need to know",
        layout: "accordion",
        allowMultiple: false,
        items: [
          { id: generateId(), question: "What is your return policy?", answer: "We offer a 30-day money-back guarantee on all purchases." },
          { id: generateId(), question: "How long does shipping take?", answer: "Standard shipping takes 3-5 business days." },
          { id: generateId(), question: "Do you offer customer support?", answer: "Yes, we provide 24/7 support via email and live chat." },
        ],
      },
    }),
  },
  {
    type: "pricing",
    label: "Price List",
    description: "Show your prices or packages side by side",
    icon: "💳",
    category: "content",
    create: () => ({
      ...baseBlock("pricing"),
      type: "pricing",
      data: {
        title: "Simple, Transparent Pricing",
        subtitle: "Choose the plan that works for you",
        layout: "cards",
        billingToggle: false,
        plans: [
          { id: generateId(), name: "Starter", price: "$9", period: "mo", description: "Perfect for individuals", features: ["5 projects", "10 GB storage", "Email support"], ctaLabel: "Get Started", ctaUrl: "#" },
          { id: generateId(), name: "Pro", price: "$29", period: "mo", description: "Best for small teams", features: ["Unlimited projects", "100 GB storage", "Priority support", "Custom domain"], highlighted: true, badge: "Most Popular", ctaLabel: "Start Free Trial", ctaUrl: "#" },
          { id: generateId(), name: "Enterprise", price: "$99", period: "mo", description: "For large organizations", features: ["Everything in Pro", "Dedicated support", "SLA guarantee", "Custom integrations"], ctaLabel: "Contact Sales", ctaUrl: "#" },
        ],
      },
    }),
  },
  {
    type: "features",
    label: "Why Choose Us",
    description: "A grid of selling points with small icons",
    icon: "✨",
    category: "content",
    create: () => ({
      ...baseBlock("features"),
      type: "features",
      data: {
        title: "Why Choose Us",
        subtitle: "Everything you need to succeed",
        layout: "grid",
        columns: 3,
        style: "card",
        items: [
          { id: generateId(), icon: "Zap", title: "Lightning Fast", description: "Optimized for performance at every level." },
          { id: generateId(), icon: "Shield", title: "Secure by Default", description: "Enterprise-grade security built in." },
          { id: generateId(), icon: "Star", title: "5-Star Support", description: "Our team is here 24/7 to help you." },
          { id: generateId(), icon: "Globe", title: "Global CDN", description: "Served fast from servers worldwide." },
          { id: generateId(), icon: "BarChart", title: "Analytics", description: "Detailed insights into your performance." },
          { id: generateId(), icon: "Settings", title: "Fully Customizable", description: "Tweak every aspect to match your brand." },
        ],
      },
    }),
  },
  {
    type: "stats",
    label: "Big Numbers",
    description: "Impressive numbers that count up — years in business, happy customers",
    icon: "📊",
    category: "content",
    create: () => ({
      ...baseBlock("stats"),
      type: "stats",
      data: {
        title: "Our Numbers",
        layout: "row",
        columns: 4,
        style: "plain",
        animate: true,
        items: [
          { id: generateId(), value: "10000", label: "Happy Clients", suffix: "+" },
          { id: generateId(), value: "500", label: "Projects Completed", suffix: "+" },
          { id: generateId(), value: "15", label: "Years Experience", suffix: "+" },
          { id: generateId(), value: "99", label: "Satisfaction Rate", suffix: "%" },
        ],
      },
    }),
  },
  {
    type: "contact",
    label: "Contact Form",
    description: "Lets visitors send you a message — lands in your inbox",
    icon: "✉️",
    category: "interactive",
    create: () => ({
      ...baseBlock("contact"),
      type: "contact",
      data: {
        title: "Get in Touch",
        subtitle: "We'd love to hear from you",
        layout: "split",
        showMap: false,
        showContactInfo: true,
        submitLabel: "Send Message",
        successMessage: "Thank you! We'll be in touch soon.",
        fields: [
          { id: generateId(), label: "Name", type: "text", required: true },
          { id: generateId(), label: "Email", type: "email", required: true },
          { id: generateId(), label: "Subject", type: "text", required: false },
          { id: generateId(), label: "Message", type: "textarea", required: true },
        ],
      },
    }),
  },
  {
    type: "embed",
    label: "Embed Anything",
    description: "Paste a link to show maps, music, or other websites",
    icon: "🔗",
    category: "media",
    create: () => ({
      ...baseBlock("embed"),
      type: "embed",
      data: { url: "", embedType: "youtube", aspectRatio: "16:9" },
    }),
  },
  {
    type: "video",
    label: "Video",
    description: "Show a YouTube, Vimeo, or uploaded video",
    icon: "🎬",
    category: "media",
    create: () => ({
      ...baseBlock("video"),
      type: "video",
      data: {
        url: "",
        videoType: "youtube",
        autoplay: false,
        muted: false,
        loop: false,
        controls: true,
        aspectRatio: "16:9",
      },
    }),
  },
  {
    type: "timeline",
    label: "Our Story",
    description: "Your business history as a year-by-year timeline",
    icon: "📅",
    category: "content",
    create: () => ({
      ...baseBlock("timeline"),
      type: "timeline",
      data: {
        title: "Our Journey",
        layout: "vertical",
        style: "card",
        items: [
          { id: generateId(), date: "2020", title: "Founded", description: "Started our journey with a small team and big dreams." },
          { id: generateId(), date: "2021", title: "First Product", description: "Launched our first product to market." },
          { id: generateId(), date: "2023", title: "1,000 Customers", description: "Reached a major milestone." },
          { id: generateId(), date: "2024", title: "Global Expansion", description: "Expanded to 50+ countries worldwide." },
        ],
      },
    }),
  },
  {
    type: "columns",
    label: "Side-by-Side Text",
    description: "Two or more columns of writing next to each other",
    icon: "⬛",
    category: "layout",
    create: () => ({
      ...baseBlock("columns"),
      type: "columns",
      data: {
        columns: 2,
        gap: "md",
        verticalAlign: "top",
        content: [
          "<h3>Column One</h3><p>Add your content for this column here.</p>",
          "<h3>Column Two</h3><p>Add your content for this column here.</p>",
        ],
      },
    }),
  },
  {
    type: "container",
    label: "Container",
    description: "Row/column layout to hold and arrange other blocks side by side",
    icon: "▦",
    category: "layout",
    create: () => ({
      ...baseBlock("container"),
      type: "container",
      data: {
        columns: [
          { id: generateId(), widthPct: 50, blocks: [] },
          { id: generateId(), widthPct: 50, blocks: [] },
        ],
        direction: "row",
        gap: "md",
        align: "stretch",
        justify: "start",
        wrapOnMobile: true,
      },
    }),
  },
  {
    type: "newsletter",
    label: "Email Signup",
    description: "Collect visitor emails for offers and updates",
    icon: "📬",
    category: "interactive",
    create: () => ({
      ...baseBlock("newsletter"),
      type: "newsletter",
      data: {
        title: "Stay in the Loop",
        description: "Get the latest updates delivered to your inbox.",
        placeholder: "Enter your email address…",
        submitLabel: "Subscribe",
        successMessage: "You're subscribed! Check your inbox.",
        layout: "inline",
      },
    }),
  },
  {
    type: "countdown",
    label: "Countdown Clock",
    description: "Ticking clock for sales, openings, and events",
    icon: "⏳",
    category: "interactive",
    create: () => ({
      ...baseBlock("countdown"),
      type: "countdown",
      data: {
        title: "Coming Soon",
        targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        layout: "boxes",
        showSeconds: true,
        labels: { days: "Days", hours: "Hours", minutes: "Minutes", seconds: "Seconds" },
      },
    }),
  },
  {
    type: "steps",
    label: "How It Works",
    description: "Numbered steps that explain your process simply",
    icon: "🚶",
    category: "content",
    create: () => ({
      ...baseBlock("steps"),
      type: "steps",
      data: {
        title: "How It Works",
        subtitle: "Get started in 3 easy steps",
        layout: "horizontal",
        style: "connected",
        items: [
          { id: generateId(), title: "Sign Up", description: "Create your free account in minutes." },
          { id: generateId(), title: "Set Up", description: "Configure your workspace and preferences." },
          { id: generateId(), title: "Launch", description: "Go live and start growing your business." },
        ],
      },
    }),
  },
  {
    type: "icon_grid",
    label: "Icon Grid",
    description: "Small icons with labels — brands you work with, what you cover",
    icon: "🔲",
    category: "content",
    create: () => ({
      ...baseBlock("icon_grid"),
      type: "icon_grid",
      data: {
        title: "Technologies We Use",
        columns: 4,
        style: "plain",
        iconSize: "md",
        items: [
          { id: generateId(), icon: "Globe", label: "Web" },
          { id: generateId(), icon: "Smartphone", label: "Mobile" },
          { id: generateId(), icon: "Database", label: "Database" },
          { id: generateId(), icon: "Cloud", label: "Cloud" },
          { id: generateId(), icon: "Shield", label: "Security" },
          { id: generateId(), icon: "Zap", label: "Performance" },
          { id: generateId(), icon: "BarChart", label: "Analytics" },
          { id: generateId(), icon: "Settings", label: "Automation" },
        ],
      },
    }),
  },
  {
    type: "footer",
    label: "Footer",
    description: "Site footer with logo, links, social icons and copyright",
    icon: "🦶",
    category: "layout",
    create: () => ({
      ...baseBlock("footer"),
      type: "footer" as const,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      data: {
        logoText: "Brand",
        tagline: "Your tagline here",
        style: "dark" as const,
        columns: [
          {
            id: generateId(),
            heading: "Company",
            links: [
              { id: generateId(), label: "About Us", url: "/about" },
              { id: generateId(), label: "Services", url: "/services" },
              { id: generateId(), label: "Contact", url: "/contact" },
            ],
          },
          {
            id: generateId(),
            heading: "Services",
            links: [
              { id: generateId(), label: "Visa Processing", url: "/services/visa" },
              { id: generateId(), label: "Work Permits", url: "/services/work-permit" },
              { id: generateId(), label: "Tour Packages", url: "/services/tours" },
            ],
          },
        ],
        socials: [],
        copyrightYear: true,
        bottomLinks: [
          { id: generateId(), label: "Privacy Policy", url: "/privacy" },
          { id: generateId(), label: "Terms", url: "/terms" },
        ],
      },
    }),
  },
  {
    type: "country_grid",
    label: "Country Grid",
    description: "Grid of country cards with flag, visa types, processing time and link",
    icon: "🌍",
    category: "content",
    create: () => ({
      ...baseBlock("country_grid"),
      type: "country_grid" as const,
      data: {
        title: "Countries We Cover",
        subtitle: "Choose a destination to see visa options and requirements.",
        columns: 4 as const,
        groupByRegion: false,
        accentColor: "#1e3a8a",
        items: [
          { id: generateId(), country: "Germany", flagEmoji: "🇩🇪", region: "Schengen Europe", visaTypes: ["Work Permit", "Job Seeker"], processingTime: "8–12 weeks", summary: "Skilled work opportunities across the EU's largest economy.", href: "/countries/germany" },
          { id: generateId(), country: "Saudi Arabia", flagEmoji: "🇸🇦", region: "GCC", visaTypes: ["Work Visa", "Visit"], processingTime: "2–4 weeks", summary: "High-demand work visas across the Gulf region.", href: "/countries/saudi-arabia" },
        ],
      },
    }),
  },
  {
    type: "eligibility_checker",
    label: "Eligibility Checker",
    description: "Interactive multi-step visa eligibility quiz with lead capture",
    icon: "✅",
    category: "interactive",
    create: () => ({
      ...baseBlock("eligibility_checker"),
      type: "eligibility_checker" as const,
      data: {
        title: "Check Your Visa Eligibility",
        subtitle: "Answer a few quick questions and get instant guidance — free.",
        accentColor: "#1e3a8a",
        submitLabel: "Check My Eligibility",
        destinations: [
          { id: generateId(), label: "Europe (Work Permit)", value: "Europe" },
          { id: generateId(), label: "GCC / Middle East", value: "GCC" },
          { id: generateId(), label: "Skilled Migration (AU/CA/NZ)", value: "Skilled Migration" },
          { id: generateId(), label: "Student Visa", value: "Student" },
        ],
      },
    }),
  },
  {
    type: "booking",
    label: "Appointment Booking",
    description: "Live availability calendar — visitors pick a slot and book",
    icon: "📅",
    category: "interactive",
    create: () => ({
      ...baseBlock("booking"),
      type: "booking" as const,
      data: {
        title: "Book an Appointment",
        subtitle: "Pick a day and time that works for you.",
        accentColor: "#4f46e5",
        daysToShow: 14,
        showPhone: true,
        showMessage: true,
        submitLabel: "Book Appointment",
      },
    }),
  },
  {
    type: "donor_group_cards",
    label: "Blood Group Cards",
    description: "8 blood-group cards with live donor counts — tap to filter the donor list",
    icon: "🩸",
    category: "interactive",
    create: () => ({
      ...baseBlock("donor_group_cards"),
      type: "donor_group_cards" as const,
      data: {
        title: "Find Donors by Blood Group",
        subtitle: "Tap a group to see available donors.",
        accentColor: "#dc2626",
        linkTarget: "#donor-list",
      },
    }),
  },
  {
    type: "donor_requests",
    label: "Urgent Blood Requests",
    description: "Latest urgent requests — 2 columns on mobile, 3 on desktop",
    icon: "🚨",
    category: "interactive",
    create: () => ({
      ...baseBlock("donor_requests"),
      type: "donor_requests" as const,
      data: {
        title: "Urgent Blood Requests",
        subtitle: "People who need blood right now. Tap to call.",
      },
    }),
  },
  {
    type: "donor_map",
    label: "Donor Map",
    description: "Interactive map of donors color-coded by availability, with GPS radius search",
    icon: "🗺️",
    category: "interactive",
    create: () => ({
      ...baseBlock("donor_map"),
      type: "donor_map" as const,
      data: {
        title: "Donors Near You",
        subtitle: "Use your location to find nearby donors, or explore the map.",
        height: 420,
      },
    }),
  },
  {
    type: "donor_list",
    label: "Donor List",
    description: "Filterable blood donor directory with availability status",
    icon: "🫀",
    category: "interactive",
    create: () => ({
      ...baseBlock("donor_list"),
      type: "donor_list" as const,
      data: {
        title: "Donors",
        accentColor: "#dc2626",
        showAddButton: true,
        addButtonLabel: "Add Donor",
        showFilters: true,
      },
    }),
  },
  {
    type: "status_tracker",
    label: "Visa Status Tracker",
    description: "Lookup form for clients to track their visa application status",
    icon: "🔎",
    category: "interactive",
    create: () => ({
      ...baseBlock("status_tracker"),
      type: "status_tracker" as const,
      data: {
        title: "Track Your Application",
        subtitle: "Enter your reference number to see live status.",
        placeholder: "Passport or reference number",
        helpText: "Your reference number is provided when you submit an application.",
        submitLabel: "Track Status",
        accentColor: "#1e3a8a",
      },
    }),
  },
];

export const blocksByCategory = blockRegistry.reduce(
  (acc, block) => {
    if (!acc[block.category]) acc[block.category] = [];
    acc[block.category].push(block);
    return acc;
  },
  {} as Record<string, BlockDefinition[]>,
);

export function getBlockDefinition(type: BlockType): BlockDefinition | undefined {
  return blockRegistry.find((b) => b.type === type);
}

export function createBlock(type: BlockType): Block | undefined {
  return getBlockDefinition(type)?.create();
}
