import { createAdminClient } from "@/lib/supabase/server";
import { FONT_OPTIONS } from "@/modules/themes/fonts";
import type { SiteDesign } from "@/modules/themes/template-types";

export interface ThemeSettings {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  headingFont: string;
  bodyFont: string;
  borderRadius: string;
}

const HEX = /^#[0-9a-fA-F]{6}$/;
const COLOR_KEYS = ["primaryColor", "secondaryColor", "accentColor", "backgroundColor", "textColor"] as const;

/**
 * Persists a suggested theme as the tenant's active theme.
 *
 * Extracted from the suggest-theme route so the automatic signup build can use
 * the same path the page-builder dialog does — a generated site on a template's
 * default palette looks like two different businesses.
 *
 * Values are re-validated here rather than trusted: in the dialog's flow they
 * make a round trip through the client, and this function is the last point
 * before they become CSS on a live site.
 */
export async function applyThemeSuggestion(
  tenantId: string,
  theme: Partial<ThemeSettings> | null | undefined,
): Promise<{ ok: true; themeId: string } | { ok: false; error: string }> {
  if (!theme) return { ok: false, error: "No theme to apply" };

  const settings = {
    primaryColor: theme.primaryColor,
    secondaryColor: theme.secondaryColor,
    accentColor: theme.accentColor,
    backgroundColor: theme.backgroundColor,
    textColor: theme.textColor,
    headingFont: theme.headingFont,
    bodyFont: theme.bodyFont,
    borderRadius: theme.borderRadius,
    containerWidth: "1200px",
  };

  if (!Object.values(settings).every(v => typeof v === "string" && v.length > 0)) {
    return { ok: false, error: "Incomplete theme — re-generate the suggestion." };
  }
  if (!COLOR_KEYS.every(k => HEX.test(settings[k] as string))) {
    return { ok: false, error: "Invalid colour value in theme." };
  }

  const admin = await createAdminClient();
  await admin.from("themes").update({ is_active: false }).eq("tenant_id", tenantId);

  const { data: created, error } = await admin
    .from("themes")
    .insert({
      tenant_id: tenantId,
      name: "AiCoder Palette",
      slug: `aicoder-${Date.now()}`,
      description: "Generated by AiCoder from the site brief.",
      author: "AiCoder",
      version: "1.0.0",
      is_active: true,
      settings,
    })
    .select("id")
    .single();

  if (error) return { ok: false, error: error.message };

  // The themes row above is history only — the live site, homepage and
  // editor all theme from site_identity (modules/themes/site-theme.ts), so a
  // palette written only to `themes` never showed up anywhere. Write it where
  // it's actually read: colours as color_overrides, fonts/roundness as
  // design_overrides.
  const s = settings as Record<string, string>;
  const knownFont = (f: string) => FONT_OPTIONS.some((o) => o.name === f) ? f : undefined;
  const px = /rem$/.test(s.borderRadius) ? parseFloat(s.borderRadius) * 16 : parseFloat(s.borderRadius);
  const roundness: SiteDesign["roundness"] = !Number.isFinite(px) ? undefined
    : px <= 1 ? "sharp" : px <= 6 ? "soft" : px <= 12 ? "rounded" : "extra";
  const design: SiteDesign = {
    ...(knownFont(s.headingFont) ? { headingFont: s.headingFont } : {}),
    ...(knownFont(s.bodyFont) ? { bodyFont: s.bodyFont } : {}),
    ...(roundness ? { roundness } : {}),
  };
  const { error: idError } = await admin.from("site_identity").upsert(
    {
      tenant_id: tenantId,
      color_overrides: {
        primary: s.primaryColor,
        secondary: s.secondaryColor,
        accent: s.accentColor,
        ring: s.primaryColor,
        background: s.backgroundColor,
        foreground: s.textColor,
      },
      design_overrides: Object.keys(design).length ? design : null,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "tenant_id" },
  );
  if (idError) return { ok: false, error: idError.message };

  return { ok: true, themeId: created.id };
}
