import { createAdminClient } from "@/lib/supabase/server";

export interface ThemeSettings {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  headingFont: string;
  bodyFont: string;
  borderRadius: string;
}

const HEX = /^#[0-9a-fA-F]{6}$/;
const COLOR_KEYS = ["primaryColor", "secondaryColor", "accentColor", "backgroundColor", "textColor"] as const;

/**
 * Persists a suggested theme as the tenant's active theme.
 *
 * Extracted from the suggest-theme route so the automatic signup build can use
 * the same path the page-builder dialog does — a generated site on a template's
 * default palette looks like two different businesses.
 *
 * Values are re-validated here rather than trusted: in the dialog's flow they
 * make a round trip through the client, and this function is the last point
 * before they become CSS on a live site.
 */
export async function applyThemeSuggestion(
  tenantId: string,
  theme: Partial<ThemeSettings> | null | undefined,
): Promise<{ ok: true; themeId: string } | { ok: false; error: string }> {
  if (!theme) return { ok: false, error: "No theme to apply" };

  const settings = {
    primaryColor: theme.primaryColor,
    secondaryColor: theme.secondaryColor,
    accentColor: theme.accentColor,
    backgroundColor: theme.backgroundColor,
    textColor: theme.textColor,
    headingFont: theme.headingFont,
    bodyFont: theme.bodyFont,
    borderRadius: theme.borderRadius,
    containerWidth: "1200px",
  };

  if (!Object.values(settings).every(v => typeof v === "string" && v.length > 0)) {
    return { ok: false, error: "Incomplete theme — re-generate the suggestion." };
  }
  if (!COLOR_KEYS.every(k => HEX.test(settings[k] as string))) {
    return { ok: false, error: "Invalid colour value in theme." };
  }

  const admin = await createAdminClient();
  await admin.from("themes").update({ is_active: false }).eq("tenant_id", tenantId);

  const { data: created, error } = await admin
    .from("themes")
    .insert({
      tenant_id: tenantId,
      name: "AiCoder Palette",
      slug: `aicoder-${Date.now()}`,
      description: "Generated by AiCoder from the site brief.",
      author: "AiCoder",
      version: "1.0.0",
      is_active: true,
      settings,
    })
    .select("id")
    .single();

  if (error) return { ok: false, error: error.message };
  return { ok: true, themeId: created.id };
}
