import { NextResponse } from "next/server";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { apiTenantId } from "@/lib/tenant/api";
import { requireModule } from "@/lib/modules/resolve-modules";
import { suggestTheme, AiCoderError } from "@/lib/aicoder/generate";
import { businessFactsSchema } from "@/lib/aicoder/brief";

/**
 * Suggests a site-wide palette and type pairing from the brief's design
 * direction, and — only on an explicit second call with `apply` — writes it.
 *
 * Theme is site-wide, so this is kept out of the page-generation flow entirely.
 * Restyling every existing page as a side effect of generating one new page
 * would be a genuinely destructive surprise, so the suggestion is surfaced on
 * its own and applied only when the user says so.
 *
 * Applying creates a NEW theme row rather than mutating the active one. The
 * previous theme stays intact and selectable, which is the whole undo story for
 * an operation that has no page-snapshot equivalent.
 */
export async function POST(req: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const tenantId = await apiTenantId();
  if (!tenantId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  if (!await requireModule(tenantId, "ai_coder")) {
    return NextResponse.json({ error: "AiCoder isn't included in this site's plan" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { facts: rawFacts, apply, theme: rawTheme } = body as {
    facts?: unknown;
    apply?: boolean;
    theme?: Record<string, string>;
  };

  // --- Apply path: persist a previously suggested theme -------------------
  if (apply) {
    if (!rawTheme) return NextResponse.json({ error: "No theme to apply" }, { status: 400 });

    const admin = await createAdminClient();
    const settings = {
      primaryColor: rawTheme.primaryColor,
      secondaryColor: rawTheme.secondaryColor,
      accentColor: rawTheme.accentColor,
      backgroundColor: rawTheme.backgroundColor,
      textColor: rawTheme.textColor,
      headingFont: rawTheme.headingFont,
      bodyFont: rawTheme.bodyFont,
      borderRadius: rawTheme.borderRadius,
      containerWidth: "1200px",
    };

    if (!Object.values(settings).every(v => typeof v === "string" && v.length > 0)) {
      return NextResponse.json({ error: "Incomplete theme — re-generate the suggestion." }, { status: 400 });
    }
    // Colours arrive from the client, so re-check the format here rather than
    // trusting that they are the ones the model produced.
    const hex = /^#[0-9a-fA-F]{6}$/;
    const colorKeys = ["primaryColor", "secondaryColor", "accentColor", "backgroundColor", "textColor"] as const;
    if (!colorKeys.every(k => hex.test(settings[k]))) {
      return NextResponse.json({ error: "Invalid colour value in theme." }, { status: 400 });
    }

    await admin.from("themes").update({ is_active: false }).eq("tenant_id", tenantId);

    const { data: created, error } = await admin
      .from("themes")
      .insert({
        tenant_id: tenantId,
        name: "AiCoder Palette",
        slug: `aicoder-${Date.now()}`,
        description: "Generated by AiCoder from the site brief.",
        author: "AiCoder",
        version: "1.0.0",
        is_active: true,
        settings,
      })
      .select("id")
      .single();

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    return NextResponse.json({ ok: true, themeId: created.id });
  }

  // --- Suggest path -------------------------------------------------------
  const factsResult = businessFactsSchema.safeParse(rawFacts);
  if (!factsResult.success) {
    return NextResponse.json({ error: "Invalid business facts — re-plan the page first." }, { status: 400 });
  }

  try {
    const theme = await suggestTheme(factsResult.data);
    return NextResponse.json({ theme });
  } catch (err) {
    if (err instanceof AiCoderError) {
      const status = err.code === "no_api_key" ? 503 : 502;
      return NextResponse.json({ error: err.message, code: err.code }, { status });
    }
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Couldn't suggest a theme" },
      { status: 500 },
    );
  }
}
