-- Fix: vendor_ledger ordering was ambiguous.
--
-- appendLedger inserts a sale, its commission and any COD fee in a single
-- statement, so all of them land with an identical created_at. Reading "the
-- newest row" by created_at alone therefore returned an arbitrary member of
-- that group, and a balance read could report the pre-commission figure as
-- the vendor's current balance. A bigint identity gives every entry a strict
-- insertion order to sort by.

alter table public.vendor_ledger
  add column if not exists seq bigint generated by default as identity;

-- Existing rows predate the column; identity backfills them in physical
-- order, which for a table this young matches insertion order.
create index if not exists vendor_ledger_vendor_seq_idx
  on public.vendor_ledger (vendor_id, seq desc);
